"""Shared contracts and finalization for context compilation."""

from .contracts import (
    CompileRequest,
    CompiledResult,
    ContextPacket,
    FormalExecutionLimits,
    ObstructionData,
    PacketKind,
    SelectionDecision,
    SourceBundle,
    SourceRef,
    TextBudget,
    TheoremKernel,
)
from .finalize import finalize_packet
from .obstruction import (
    ArtifactReader,
    AttemptEvidence,
    CharHeuristicTokenCounter,
    DiagnosticEvidence,
    FailedState,
    MappingArtifactReader,
    ObstructionCompilation,
    ObstructionPayload,
    ObservedFailure,
    SuspectedCause,
    TokenCounter,
    compile_obstruction,
)

__all__ = [
    "ArtifactReader",
    "AttemptEvidence",
    "CharHeuristicTokenCounter",
    "CompileRequest",
    "CompiledResult",
    "ContextPacket",
    "DiagnosticEvidence",
    "FailedState",
    "FormalExecutionLimits",
    "MappingArtifactReader",
    "ObstructionCompilation",
    "ObstructionData",
    "ObstructionPayload",
    "ObservedFailure",
    "PacketKind",
    "SelectionDecision",
    "SourceBundle",
    "SourceRef",
    "SuspectedCause",
    "TextBudget",
    "TheoremKernel",
    "TokenCounter",
    "compile_obstruction",
    "finalize_packet",
]